import { Injectable } from '@angular/core';
import { Category } from '../features/models/category.model';
import { Product } from '../features/models/product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  // 4 categories exactly
  readonly categories: Category[] = [
    { id: 1, name: 'Smartphones' },
    { id: 2, name: 'Laptops' },
    { id: 3, name: 'Headphones' },
    { id: 4, name: 'Tablets' },
  ];


  readonly products: Product[] = [
    // Smartphones (categoryId: 1)
    {
      id: 1001,
      categoryId: 1,
      name: 'Apple iPhone 15 128GB (черный)',
      description: 'OLED-дисплей и мощный чип. Отлично подходит для фото/видео и игр.',
      price: 365000,
      rating: 4.9,
      image: 'products/phone1/main.jpg',
      images: ['products/phone1/1.jpg', 'products/phone1/2.jpg', 'products/phone1/3.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-iphone-15-128gb-chernyi-113137790/',
      likes: 0,
    },
    {
      id: 1002,
      categoryId: 1,
      name: 'Samsung Galaxy S24 Ultra 12/256 (черный)',
      description: 'Флагман с отличной камерой и большим экраном. Подходит для тяжелых задач.',
      price: 499000,
      rating: 4.8,
      image: 'products/phone2/main.jpg',
      images: ['products/phone2/1.jpg', 'products/phone2/2.jpg', 'products/phone2/3.jpg'],
      link: 'https://kaspi.kz/shop/p/samsung-galaxy-s24-ultra-5g-12-gb-256-gb-chernyi-116044354/',
      likes: 0,
    },
    {
      id: 1003,
      categoryId: 1,
      name: 'Xiaomi Redmi Note 13 Pro 8/128',
      description: 'Сбалансированный смартфон на каждый день. Хороший экран и автономность.',
      price: 129000,
      rating: 4.7,
      image: 'products/phone3/main.jpg',
      images: ['products/phone3/1.jpg', 'products/phone3/2.jpg', 'products/phone3/3.jpg'],
      link: 'https://kaspi.kz/shop/p/xiaomi-redmi-note-13-pro-4g-8-gb-128-gb-chernyi-117949575/',
      likes: 0,
    },
    {
      id: 1004,
      categoryId: 1,
      name: 'Apple iPhone 14 128GB',
      description: 'Надежный iPhone для повседневных задач. Отличная камера и производительность.',
      price: 299000,
      rating: 4.8,
      image: 'products/phone4/main.jpg',
      images: ['products/phone4/1.jpg', 'products/phone4/2.jpg', 'products/phone4/3.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-iphone-14-128gb-chernyi-106363140/',
      likes: 0,
    },
    {
      id: 1005,
      categoryId: 1,
      name: 'Samsung Galaxy A55 8/256',
      description: 'Отличный mid-range с хорошей камерой и экраном. Для учебы и работы.',
      price: 199000,
      rating: 4.7,
      image: 'products/phone5/main.jpg',
      images: ['products/phone5/1.jpg', 'products/phone5/2.jpg', 'products/phone5/3.jpg'],
      link: 'https://kaspi.kz/shop/p/samsung-galaxy-a55-5g-8-gb-256-gb-chernyi-120218795/',
      likes: 0,
    },

    // Laptops (categoryId: 2)
    {
      id: 2001,
      categoryId: 2,
      name: 'Lenovo IdeaPad 3 15.6" / 8GB / 512GB SSD',
      description: 'Для учебы и офиса: браузер, документы, видео. SSD ускоряет работу.',
      price: 219000,
      rating: 4.6,
      image: 'products/laptop1/main.jpg',
      images: ['products/laptop1/1.jpg', 'products/laptop1/2.jpg', 'products/laptop1/3.jpg'],
      link: 'https://kaspi.kz/shop/p/lenovo-ideapad-3-15-6-8-gb-ssd-512-gb-win-11-15iau7-82rk00ewrk-107333284/',
      likes: 0,
    },
    {
      id: 2002,
      categoryId: 2,
      name: 'Acer Aspire 5 15.6" / 16GB / 512GB SSD',
      description: 'Универсальный ноутбук для работы и учебы. Хороший баланс цены и мощности.',
      price: 259000,
      rating: 4.6,
      image: 'products/laptop2/main.jpg',
      images: ['products/laptop2/1.jpg', 'products/laptop2/2.jpg', 'products/laptop2/3.jpg'],
      link: 'https://kaspi.kz/shop/p/acer-aspire-5-a515-58gm-15-6-16-gb-ssd-512-gb-win-11-nx-khveu-002-114596180/',
      likes: 0,
    },
    {
      id: 2003,
      categoryId: 2,
      name: 'HP 15 / 8GB / 256GB SSD',
      description: 'Базовый ноутбук для ежедневных задач. Легкий и удобный для учебы.',
      price: 199000,
      rating: 4.5,
      image: 'products/laptop3/main.jpg',
      images: ['products/laptop3/1.jpg', 'products/laptop3/2.jpg', 'products/laptop3/3.jpg'],
      link: 'https://kaspi.kz/shop/p/hp-15-fc0014ci-15-6-8-gb-ssd-256-gb-win-11-117372593/',
      likes: 0,
    },
    {
      id: 2004,
      categoryId: 2,
      name: 'ASUS VivoBook 15 / 16GB / 512GB SSD',
      description: 'Быстрый ноутбук для многозадачности. Подойдет для разработки и офисных задач.',
      price: 289000,
      rating: 4.6,
      image: 'products/laptop4/main.jpg',
      images: ['products/laptop4/1.jpg', 'products/laptop4/2.jpg', 'products/laptop4/3.jpg'],
      link: 'https://kaspi.kz/shop/p/asus-vivobook-15-x1504za-15-6-16-gb-ssd-512-gb-win-11-90nb1022-m00b70-116932167/',
      likes: 0,
    },
    {
      id: 2005,
      categoryId: 2,
      name: 'Apple MacBook Air M1 8/256',
      description: 'Тихий, быстрый и автономный. Отлично для учебы, работы и кодинга.',
      price: 399000,
      rating: 4.9,
      image: 'products/laptop5/main.jpg',
      images: ['products/laptop5/1.jpg', 'products/laptop5/2.jpg', 'products/laptop5/3.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-m1-8-gb-ssd-256-gb-mgn63ru-a-seryi-100397891/',
      likes: 0,
    },

    // Headphones (categoryId: 3)
    {
      id: 3001,
      categoryId: 3,
      name: 'Sony WH-1000XM5 (черный)',
      description: 'Топовое шумоподавление и комфорт. Отлично для поездок и работы.',
      price: 159000,
      rating: 4.9,
      image: 'products/head1/main.jpg',
      images: ['products/head1/1.jpg', 'products/head1/2.jpg', 'products/head1/3.jpg'],
      link: 'https://kaspi.kz/shop/p/naushniki-sony-wh-1000xm5-chernyi-105259822/',
      likes: 0,
    },
    {
      id: 3002,
      categoryId: 3,
      name: 'Apple AirPods Pro 2 (MagSafe)',
      description: 'TWS-наушники с шумоподавлением. Отличны для звонков и музыки.',
      price: 129000,
      rating: 4.8,
      image: 'products/head2/main.jpg',
      images: ['products/head2/1.jpg', 'products/head2/2.jpg', 'products/head2/3.jpg'],
      link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-pro-2nd-generation-with-wireless-magsafe-charging-case-belyi-113677582/',
      likes: 0,
    },
    {
      id: 3003,
      categoryId: 3,
      name: 'JBL Tune 510BT',
      description: 'Легкие беспроводные наушники на каждый день. Хороший звук за свою цену.',
      price: 19990,
      rating: 4.6,
      image: 'products/head3/main.jpg',
      images: ['products/head3/1.jpg', 'products/head3/2.jpg', 'products/head3/3.jpg'],
      link: 'https://kaspi.kz/shop/p/jbl-tune-510bt-chernyi-101525300/',
      likes: 0,
    },
    {
      id: 3004,
      categoryId: 3,
      name: 'Samsung Galaxy Buds2 Pro',
      description: 'Компактные наушники с качественным звуком. Удобны для спорта и улицы.',
      price: 79990,
      rating: 4.7,
      image: 'products/head4/main.jpg',
      images: ['products/head4/1.jpg', 'products/head4/2.jpg', 'products/head4/3.jpg'],
      link: 'https://kaspi.kz/shop/p/samsung-galaxy-buds2-pro-grafit-106170600/',
      likes: 0,
    },
    {
      id: 3005,
      categoryId: 3,
      name: 'HyperX Cloud II (проводные)',
      description: 'Отличная гарнитура для игр и общения. Комфорт и хороший микрофон.',
      price: 49990,
      rating: 4.8,
      image: 'products/head5/main.jpg',
      images: ['products/head5/1.jpg', 'products/head5/2.jpg', 'products/head5/3.jpg'],
      link: 'https://kaspi.kz/shop/p/hyperx-cloud-ii-krasnyi-chernyi-100104853/',
      likes: 0,
    },

    
    {
      id: 4001,
      categoryId: 4,
      name: 'Apple iPad 10.9 (10th gen) 64GB Wi-Fi',
      description: 'Отличный планшет для учебы, заметок и видео. Большой яркий экран.',
      price: 229000,
      rating: 4.8,
      image: 'products/tab1/main.jpg',
      images: ['products/tab1/1.jpg', 'products/tab1/2.jpg', 'products/tab1/3.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-ipad-10-9-2022-wi-fi-64gb-serebristyi-106844329/',
      likes: 0,
    },
    {
      id: 4002,
      categoryId: 4,
      name: 'Samsung Galaxy Tab S9 FE',
      description: 'Планшет для работы и развлечений. Поддержка пера и удобный экран.',
      price: 259000,
      rating: 4.7,
      image: 'products/tab2/main.jpg',
      images: ['products/tab2/1.jpg', 'products/tab2/2.jpg', 'products/tab2/3.jpg'],
      link: 'https://kaspi.kz/shop/p/samsung-galaxy-tab-s9-fe-10-9-8-gb-128-gb-seryi-114700512/',
      likes: 0,
    },
    {
      id: 4003,
      categoryId: 4,
      name: 'Xiaomi Pad 6 8/256',
      description: 'Быстрый планшет с хорошим экраном. Подходит для учебы и мультимедиа.',
      price: 189000,
      rating: 4.7,
      image: 'products/tab3/main.jpg',
      images: ['products/tab3/1.jpg', 'products/tab3/2.jpg', 'products/tab3/3.jpg'],
      link: 'https://kaspi.kz/shop/p/xiaomi-pad-6-11-0-8-gb-256-gb-sinii-112926824/',
      likes: 0,
    },
    {
      id: 4004,
      categoryId: 4,
      name: 'Huawei MatePad 11',
      description: 'Планшет с большим дисплеем и хорошей автономностью. Для учебы и работы.',
      price: 199000,
      rating: 4.6,
      image: 'products/tab4/main.jpg',
      images: ['products/tab4/1.jpg', 'products/tab4/2.jpg', 'products/tab4/3.jpg'],
      link: 'https://kaspi.kz/shop/p/huawei-matepad-11-2023-6-gb-128-gb-seryi-113255744/',
      likes: 0,
    },
    {
      id: 4005,
      categoryId: 4,
      name: 'Lenovo Tab P11',
      description: 'Доступный планшет для видео и учебы. Хороший экран и базовая производительность.',
      price: 129000,
      rating: 4.5,
      image: 'products/tab5/main.jpg',
      images: ['products/tab5/1.jpg', 'products/tab5/2.jpg', 'products/tab5/3.jpg'],
      link: 'https://kaspi.kz/shop/p/lenovo-tab-p11-2nd-gen-6-gb-128-gb-seryi-112693108/',
      likes: 0,
    },
  ];

  getProductsByCategory(categoryId: number): Product[] {
    return this.products.filter(p => p.categoryId === categoryId);
  }
}